// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiV1BoardAllBoardData, GetApiV1BoardAllBoardResponses, GetApiV1BoardGetBoardCreatorData, GetApiV1BoardGetBoardCreatorErrors, GetApiV1BoardGetBoardCreatorResponses, GetApiV1PostGetPostUnderData, GetApiV1PostGetPostUnderErrors, GetApiV1PostGetPostUnderResponses, GetApiV1SystemCountData, GetApiV1SystemCountResponses, GetApiV1UserInfoData, GetApiV1UserInfoResponses, GetPingData, GetPingResponses, GetSchemaV1IndexData, GetSchemaV1IndexResponses, PostApiV1PostPostPostData, PostApiV1PostPostPostResponses, PostApiV1UserLoginData, PostApiV1UserLoginErrors, PostApiV1UserLoginResponses, PostApiV1UserRegisterData, PostApiV1UserRegisterResponses, PutApiV1UserChangePasswordData, PutApiV1UserChangePasswordErrors, PutApiV1UserChangePasswordResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getPing = <ThrowOnError extends boolean = false>(options?: Options<GetPingData, ThrowOnError>) => (options?.client ?? client).get<GetPingResponses, unknown, ThrowOnError>({ url: '/ping', ...options });

export const getApiV1SystemCount = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1SystemCountData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1SystemCountResponses, unknown, ThrowOnError>({ url: '/api/v1/system/count', ...options });

export const getApiV1BoardAllBoard = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1BoardAllBoardData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1BoardAllBoardResponses, unknown, ThrowOnError>({ url: '/api/v1/board/all-board', ...options });

export const getApiV1BoardGetBoardCreator = <ThrowOnError extends boolean = false>(options: Options<GetApiV1BoardGetBoardCreatorData, ThrowOnError>) => (options.client ?? client).get<GetApiV1BoardGetBoardCreatorResponses, GetApiV1BoardGetBoardCreatorErrors, ThrowOnError>({ url: '/api/v1/board/get-board-creator', ...options });

export const postApiV1PostPostPost = <ThrowOnError extends boolean = false>(options: Options<PostApiV1PostPostPostData, ThrowOnError>) => (options.client ?? client).post<PostApiV1PostPostPostResponses, unknown, ThrowOnError>({
    url: '/api/v1/post/post-post',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiV1PostGetPostUnder = <ThrowOnError extends boolean = false>(options: Options<GetApiV1PostGetPostUnderData, ThrowOnError>) => (options.client ?? client).get<GetApiV1PostGetPostUnderResponses, GetApiV1PostGetPostUnderErrors, ThrowOnError>({ url: '/api/v1/post/get-post-under', ...options });

/**
 * Login, server responses with Http Result along with session cookie.
 */
export const postApiV1UserLogin = <ThrowOnError extends boolean = false>(options: Options<PostApiV1UserLoginData, ThrowOnError>) => (options.client ?? client).post<PostApiV1UserLoginResponses, PostApiV1UserLoginErrors, ThrowOnError>({
    url: '/api/v1/user/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Changes password. Server reads session cookie and old password in body. If matches, user's password'd be changed.
 */
export const putApiV1UserChangePassword = <ThrowOnError extends boolean = false>(options: Options<PutApiV1UserChangePasswordData, ThrowOnError>) => (options.client ?? client).put<PutApiV1UserChangePasswordResponses, PutApiV1UserChangePasswordErrors, ThrowOnError>({
    url: '/api/v1/user/change-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Gets information of current logged in user.
 */
export const getApiV1UserInfo = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1UserInfoData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1UserInfoResponses, unknown, ThrowOnError>({ url: '/api/v1/user/info', ...options });

/**
 * Registers a new user, then auto login.
 */
export const postApiV1UserRegister = <ThrowOnError extends boolean = false>(options: Options<PostApiV1UserRegisterData, ThrowOnError>) => (options.client ?? client).post<PostApiV1UserRegisterResponses, unknown, ThrowOnError>({
    url: '/api/v1/user/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getSchemaV1Index = <ThrowOnError extends boolean = false>(options?: Options<GetSchemaV1IndexData, ThrowOnError>) => (options?.client ?? client).get<GetSchemaV1IndexResponses, unknown, ThrowOnError>({ url: '/schema/v1/index', ...options });
