// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5049/' | (string & {});
};

export type Board = {
    id?: number | string;
    name: string;
    description: string;
    moderators?: null | Array<User>;
    op: User;
    opId?: number | string;
    creator: User;
    creatorId?: number | string;
    createdAt?: string;
    tags?: null | Array<Tag>;
    posts?: Array<Post>;
};

export type BoardBody = {
    id?: number | string;
    name?: null | string;
    description?: null | string;
    posts?: null | Array<PostBody>;
    creator?: null | UserBody;
    op?: null | UserBody;
    moderators?: null | Array<UserBody>;
};

export type ChangePasswordPayload = {
    oldPassword: string;
    newPassword: string;
};

export type IndexPageSchema = {
    boards: Array<BoardBody>;
    user: null | UserBody;
};

export type LoginPayload = {
    username: string;
    password?: null | string;
};

export type Post = {
    id?: number | string;
    title: string;
    content: string;
    tags?: null | Array<Tag>;
    poster?: null | User;
    posterId?: null | number | string;
    createdAt?: string;
    boardAssociated?: Board;
    boardAssociatedId?: number | string;
    replies?: null | Array<Reply>;
};

export type PostBody = {
    id?: null | number | string;
    title?: null | string;
    content?: null | string;
    poster?: null | UserBody;
    createdAt?: null | string;
    tags?: null | Array<TagBody>;
    replies?: null | Array<ReplyBody>;
};

export type PostPostPayload = {
    title: string;
    content: string;
    under: number | string;
};

export type RegisterPayload = {
    username: string;
    email?: null | string;
    password?: null | string;
};

export type Reply = {
    id?: number | string;
    content: string;
    creator?: null | User;
    creatorId?: null | number | string;
    repliedUnder: Post;
    repliedUnderId?: number | string;
    repliedAt: string;
};

export type ReplyBody = {
    id?: number | string;
    content?: null | string;
    creator?: null | UserBody;
    repliedAt?: null | string;
};

export type Tag = {
    id?: number | string;
    name: string;
    creator?: null | User;
    creatorId?: null | number | string;
    boardsUtilizing?: null | Array<Board>;
    postsUtilizing?: null | Array<Post>;
};

export type TagBody = {
    id?: null | number | string;
    name?: null | string;
};

export type User = {
    id?: number | string;
    username: string;
    password?: null | string;
    email?: null | string;
    createdAt: string;
    isModeratorOf?: null | Array<Board>;
    postsPosted?: null | Array<Post>;
    repliesReplied?: null | Array<Reply>;
    isOpOf?: null | Array<Board>;
    isCreatorOf?: null | Array<Board>;
    isTagCreatorOf?: null | Array<Tag>;
};

export type UserBody = {
    id?: number | string;
    username?: null | string;
    email?: null | string;
};

export type UserInfoResponse = {
    id: number | string;
    username: string;
    email: null | string;
    createdAt: string;
};

export type GetPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ping';
};

export type GetPingResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetPingResponse = GetPingResponses[keyof GetPingResponses];

export type GetApiV1SystemCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/count';
};

export type GetApiV1SystemCountResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1BoardAllBoardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/board/all-board';
};

export type GetApiV1BoardAllBoardResponses = {
    /**
     * OK
     */
    200: Array<BoardBody>;
};

export type GetApiV1BoardAllBoardResponse = GetApiV1BoardAllBoardResponses[keyof GetApiV1BoardAllBoardResponses];

export type GetApiV1BoardGetBoardCreatorData = {
    body?: never;
    path?: never;
    query: {
        id: number | string;
    };
    url: '/api/v1/board/get-board-creator';
};

export type GetApiV1BoardGetBoardCreatorErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiV1BoardGetBoardCreatorResponses = {
    /**
     * OK
     */
    200: UserBody;
};

export type GetApiV1BoardGetBoardCreatorResponse = GetApiV1BoardGetBoardCreatorResponses[keyof GetApiV1BoardGetBoardCreatorResponses];

export type PostApiV1PostPostPostData = {
    body: PostPostPayload;
    path?: never;
    query?: never;
    url: '/api/v1/post/post-post';
};

export type PostApiV1PostPostPostResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1PostGetPostUnderData = {
    body?: never;
    path?: never;
    query: {
        boardId: number | string;
    };
    url: '/api/v1/post/get-post-under';
};

export type GetApiV1PostGetPostUnderErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type GetApiV1PostGetPostUnderResponses = {
    /**
     * OK
     */
    200: Array<Post>;
};

export type GetApiV1PostGetPostUnderResponse = GetApiV1PostGetPostUnderResponses[keyof GetApiV1PostGetPostUnderResponses];

export type PostApiV1UserLoginData = {
    body: LoginPayload;
    path?: never;
    query?: never;
    url: '/api/v1/user/login';
};

export type PostApiV1UserLoginErrors = {
    /**
     * Bad Request
     */
    400: string;
};

export type PostApiV1UserLoginError = PostApiV1UserLoginErrors[keyof PostApiV1UserLoginErrors];

export type PostApiV1UserLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiV1UserChangePasswordData = {
    body: ChangePasswordPayload;
    path?: never;
    query?: never;
    url: '/api/v1/user/change-password';
};

export type PutApiV1UserChangePasswordErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type PutApiV1UserChangePasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1UserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/info';
};

export type GetApiV1UserInfoResponses = {
    /**
     * OK
     */
    200: UserInfoResponse;
};

export type GetApiV1UserInfoResponse = GetApiV1UserInfoResponses[keyof GetApiV1UserInfoResponses];

export type PostApiV1UserRegisterData = {
    body: RegisterPayload;
    path?: never;
    query?: never;
    url: '/api/v1/user/register';
};

export type PostApiV1UserRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetSchemaV1IndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/schema/v1/index';
};

export type GetSchemaV1IndexResponses = {
    /**
     * OK
     */
    200: IndexPageSchema;
};

export type GetSchemaV1IndexResponse = GetSchemaV1IndexResponses[keyof GetSchemaV1IndexResponses];
