// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UltimateForum.Server;

#nullable disable

namespace UltimateForum.Server.Migrations
{
    [DbContext(typeof(UltimateForumDbContext))]
    [Migration("20260402033825_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("BoardTag", b =>
                {
                    b.Property<long>("BoardsUtilizingId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BoardsUtilizingId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("BoardTag");
                });

            modelBuilder.Entity("BoardUser", b =>
                {
                    b.Property<long>("IsModeratorOfId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModeratorsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IsModeratorOfId", "ModeratorsId");

                    b.HasIndex("ModeratorsId");

                    b.ToTable("BoardUser");
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.Property<long>("PostsUtilizingId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostsUtilizingId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("PostTag");
                });

            modelBuilder.Entity("UltimateForum.Server.Models.Board", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OpId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OpId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("UltimateForum.Server.Models.Post", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PosterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("UltimateForum.Server.Models.Reply", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RepliedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("UltimateForum.Server.Models.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Name");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("UltimateForum.Server.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BoardTag", b =>
                {
                    b.HasOne("UltimateForum.Server.Models.Board", null)
                        .WithMany()
                        .HasForeignKey("BoardsUtilizingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltimateForum.Server.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BoardUser", b =>
                {
                    b.HasOne("UltimateForum.Server.Models.Board", null)
                        .WithMany()
                        .HasForeignKey("IsModeratorOfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltimateForum.Server.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModeratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.HasOne("UltimateForum.Server.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostsUtilizingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltimateForum.Server.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UltimateForum.Server.Models.Board", b =>
                {
                    b.HasOne("UltimateForum.Server.Models.User", "Creator")
                        .WithMany("IsCreatorOf")
                        .HasForeignKey("CreatorId")
                        .IsRequired();

                    b.HasOne("UltimateForum.Server.Models.User", "Op")
                        .WithMany("IsOpOf")
                        .HasForeignKey("OpId")
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Op");
                });

            modelBuilder.Entity("UltimateForum.Server.Models.Post", b =>
                {
                    b.HasOne("UltimateForum.Server.Models.User", "Poster")
                        .WithMany("PostsPosted")
                        .HasForeignKey("Id")
                        .IsRequired();

                    b.Navigation("Poster");
                });

            modelBuilder.Entity("UltimateForum.Server.Models.Reply", b =>
                {
                    b.HasOne("UltimateForum.Server.Models.User", "Creator")
                        .WithMany("RepliesReplied")
                        .HasForeignKey("CreatorId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("UltimateForum.Server.Models.Tag", b =>
                {
                    b.HasOne("UltimateForum.Server.Models.User", "Creator")
                        .WithMany("IsTagCreatorOf")
                        .HasForeignKey("CreatorId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("UltimateForum.Server.Models.User", b =>
                {
                    b.Navigation("IsCreatorOf");

                    b.Navigation("IsOpOf");

                    b.Navigation("IsTagCreatorOf");

                    b.Navigation("PostsPosted");

                    b.Navigation("RepliesReplied");
                });
#pragma warning restore 612, 618
        }
    }
}
